<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 pausly new.glb --transform --types
-->

<script lang="ts">
  import * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Parenting Pose' | 'push-ups' | 'squats'
  type GLTFResult = {
    nodes: {
      head_1: THREE.Mesh
      face_1: THREE.Mesh
      neck_upper: THREE.Mesh
      neck_1: THREE.Mesh
      neck_base: THREE.Mesh
      stomach_top: THREE.Mesh
      pelvis001: THREE.Mesh
      pelvis_top: THREE.Mesh
      foot_jointL: THREE.Mesh
      toesL: THREE.Mesh
      ankleL: THREE.Mesh
      heelL: THREE.Mesh
      lower_kneeL: THREE.Mesh
      lower_legL: THREE.Mesh
      hipL: THREE.Mesh
      upper_kneeL: THREE.Mesh
      upper_legL: THREE.Mesh
      clavicleL: THREE.Mesh
      palmL_1: THREE.Mesh
      wristL: THREE.Mesh
      elbowL: THREE.Mesh
      lower_armL: THREE.Mesh
      shoulderL_2: THREE.Mesh
      upper_armL_1: THREE.Mesh
      chest001: THREE.SkinnedMesh
      stomach_pipes: THREE.SkinnedMesh
      pelvis: THREE.Mesh
      Sphere: THREE.Mesh
      Sphere004: THREE.Mesh
      root: THREE.Bone
      ['MCH-torsoparent']: THREE.Bone
      ['MCH-hand_ikparentL']: THREE.Bone
      ['MCH-upper_arm_ik_targetparentL']: THREE.Bone
      ['MCH-hand_ikparentR']: THREE.Bone
      ['MCH-upper_arm_ik_targetparentR']: THREE.Bone
      ['MCH-foot_ikparentL']: THREE.Bone
      ['MCH-thigh_ik_targetparentL']: THREE.Bone
      ['MCH-foot_ikparentR']: THREE.Bone
      ['MCH-thigh_ik_targetparentR']: THREE.Bone
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/pausly new-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
  const fleshMaterial = new THREE.MeshToonMaterial({
    color: '#FFE893',
  })
  const metalMaterial = new THREE.MeshToonMaterial({
    color: '#444',
  })

  let replacedMaterials = false
  const replaceMaterial = (nodes: THREE.Mesh[]) => {
    for (const node of nodes) {
      if (node.type === 'Mesh') {
        console.log(node.material)
        if (
          node.name.match(/head|shoulder|knee|top|hip|clavicle|elbow|wrist|ankle|foot_joint|neck/i)
        ) {
          node.material = metalMaterial
        } else {
          node.material = fleshMaterial
        }
      }
      if (node.children && node.children.length > 0) {
        replaceMaterial(node.children as any)
      }
    }
  }
  $: if ($gltf) {
    console.log($gltf)
    if (!replacedMaterials) {
      replaceMaterial(Object.values($gltf.nodes) as any)
    }
    replacedMaterials = true
  }
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="original_metarig">
        <T.Group name="spine" position={[0, 0.91, -0.05]} rotation={[0.25, 0, 0]}>
          <T.Group name="spine001" position={[0, 0.14, 0]} rotation={[-0.27, 0, 0]}>
            <T.Group name="spine002" position={[0, 0.12, 0]} rotation={[-0.17, 0, 0]}>
              <T.Group name="spine003" position={[0, 0.14, 0]} rotation={[0.36, 0, 0]}>
                <T.Group name="spine004" position={[0, 0.19, 0]} rotation={[0.1, 0, 0]}>
                  <T.Group name="spine005" position={[0, 0.06, 0]} rotation={[-0.24, 0, 0]}>
                    <T.Group name="spine006" position={[0, 0.06, 0]} rotation={[-0.03, 0, 0]}>
                      <T.Group name="face" />
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group name="shoulderL_1" position={[0.12, 0.15, 0]} rotation={[-1.75, 0, -1.4]}>
                  <T.Group name="upper_armL" position={[0, 0.07, 0]} rotation={[-2.97, 1.46, 2.37]}>
                    <T.Group name="forearmL" position={[0, 0.29, 0]} rotation={[0.37, 0.03, 0.03]}>
                      <T.Group
                        name="handL"
                        position={[0, 0.27, 0]}
                        rotation={[-0.06, -0.01, -0.06]}
                      >
                        <T.Group
                          name="palm01L"
                          position={[0, 0.04, 0.02]}
                          rotation={[-2.7, 1.56, 2.85]}
                        >
                          <T.Group
                            name="f_index01L_1"
                            position={[0, 0.06, 0]}
                            rotation={[0.35, 0.04, -0.15]}
                          >
                            <T.Group
                              name="f_index02L_1"
                              position={[0, 0.04, 0]}
                              rotation={[0.16, -0.01, -0.01]}
                            >
                              <T.Group
                                name="f_index03L_1"
                                position={[0, 0.03, 0]}
                                rotation={[0.23, -0.02, -0.06]}
                              />
                            </T.Group>
                          </T.Group>
                          <T.Group
                            name="thumb01L_1"
                            position={[0, -0.01, 0.02]}
                            rotation={[-1.55, 1.26, 1.99]}
                          >
                            <T.Group
                              name="thumb02L_1"
                              position={[0, 0.04, 0]}
                              rotation={[0.32, -0.04, -0.14]}
                            >
                              <T.Group
                                name="thumb03L_1"
                                position={[0, 0.03, 0]}
                                rotation={[0.03, 0, -0.08]}
                              />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                        <T.Group
                          name="palm02L"
                          position={[-0.01, 0.04, 0]}
                          rotation={[-1.49, 1.54, 1.45]}
                        >
                          <T.Group
                            name="f_middle01L_1"
                            position={[0, 0.06, 0]}
                            rotation={[0.44, 0.06, -0.04]}
                          >
                            <T.Group
                              name="f_middle02L_1"
                              position={[0, 0.04, 0]}
                              rotation={[0.24, -0.06, 0.01]}
                            >
                              <T.Group
                                name="f_middle03L_1"
                                position={[0, 0.03, 0]}
                                rotation={[0.12, -0.04, -0.02]}
                              />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                        <T.Group
                          name="palm04L"
                          position={[0, 0.03, -0.02]}
                          rotation={[-0.43, 1.56, 0.24]}
                        >
                          <T.Group
                            name="f_pinky01L_1"
                            position={[0, 0.07, 0]}
                            rotation={[0.72, -0.12, 0.05]}
                          >
                            <T.Group
                              name="f_pinky02L_1"
                              position={[0, 0.03, 0]}
                              rotation={[0.09, -0.02, -0.03]}
                            >
                              <T.Group
                                name="f_pinky03L_1"
                                position={[0, 0.02, 0]}
                                rotation={[0.17, -0.03, -0.03]}
                              />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                      </T.Group>
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group name="shoulderR_1" position={[-0.12, 0.15, 0]} rotation={[-1.75, 0, 1.4]}>
                  <T.Group
                    name="upper_armR"
                    position={[0, 0.07, 0]}
                    rotation={[-2.97, -1.46, -2.37]}
                  >
                    <T.Group
                      name="forearmR"
                      position={[0, 0.29, 0]}
                      rotation={[0.37, -0.03, -0.03]}
                    >
                      <T.Group name="handR" position={[0, 0.27, 0]} rotation={[-0.06, 0.01, 0.06]}>
                        <T.Group
                          name="palm01R"
                          position={[0, 0.04, 0.02]}
                          rotation={[-2.7, -1.56, -2.85]}
                        >
                          <T.Group
                            name="f_index01R_1"
                            position={[0, 0.06, 0]}
                            rotation={[0.35, -0.04, 0.15]}
                          >
                            <T.Group
                              name="f_index02R_1"
                              position={[0, 0.04, 0]}
                              rotation={[0.16, 0.01, 0.01]}
                            >
                              <T.Group
                                name="f_index03R_1"
                                position={[0, 0.03, 0]}
                                rotation={[0.23, 0.02, 0.06]}
                              />
                            </T.Group>
                          </T.Group>
                          <T.Group
                            name="thumb01R_1"
                            position={[0, -0.01, 0.02]}
                            rotation={[-1.55, -1.26, -1.99]}
                          >
                            <T.Group
                              name="thumb02R_1"
                              position={[0, 0.04, 0]}
                              rotation={[0.32, 0.04, 0.14]}
                            >
                              <T.Group
                                name="thumb03R_1"
                                position={[0, 0.03, 0]}
                                rotation={[0.03, 0, 0.08]}
                              />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                        <T.Group
                          name="palm02R"
                          position={[0.01, 0.04, 0]}
                          rotation={[-1.49, -1.54, -1.45]}
                        >
                          <T.Group
                            name="f_middle01R_1"
                            position={[0, 0.06, 0]}
                            rotation={[0.44, -0.06, 0.04]}
                          >
                            <T.Group
                              name="f_middle02R_1"
                              position={[0, 0.04, 0]}
                              rotation={[0.24, 0.06, -0.01]}
                            >
                              <T.Group
                                name="f_middle03R_1"
                                position={[0, 0.03, 0]}
                                rotation={[0.12, 0.04, 0.02]}
                              />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                        <T.Group
                          name="palm04R"
                          position={[0, 0.03, -0.02]}
                          rotation={[-0.43, -1.56, -0.24]}
                        >
                          <T.Group
                            name="f_pinky01R_1"
                            position={[0, 0.07, 0]}
                            rotation={[0.72, 0.12, -0.05]}
                          >
                            <T.Group
                              name="f_pinky02R_1"
                              position={[0, 0.03, 0]}
                              rotation={[0.09, 0.02, 0.03]}
                            >
                              <T.Group
                                name="f_pinky03R_1"
                                position={[0, 0.02, 0]}
                                rotation={[0.17, 0.03, 0.03]}
                              />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                      </T.Group>
                    </T.Group>
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
          <T.Group name="pelvisL" rotation={[-2.03, -0.82, -2.24]} />
          <T.Group name="pelvisR" rotation={[-2.03, 0.82, 2.24]} />
          <T.Group name="thighL" position={[0.09, 0.03, 0.03]} rotation={[2.85, 0, -0.06]}>
            <T.Group name="shinL" position={[0, 0.42, 0]} rotation={[0.07, 0.01, 0.05]}>
              <T.Group name="footL" position={[0, 0.44, 0]} rotation={[-1.18, -0.01, 0]}>
                <T.Group name="toeL" position={[0, 0.15, 0]} rotation={[2.72, 0, -Math.PI]} />
                <T.Group
                  name="heel02L"
                  position={[-0.03, 0.01, 0.08]}
                  rotation={[2.72, 0, -Math.PI / 2]}
                />
              </T.Group>
            </T.Group>
          </T.Group>
          <T.Group name="thighR" position={[-0.09, 0.03, 0.03]} rotation={[2.85, 0, 0.06]}>
            <T.Group name="shinR" position={[0, 0.42, 0]} rotation={[0.07, -0.01, -0.05]}>
              <T.Group name="footR" position={[0, 0.44, 0]} rotation={[-1.18, 0.01, 0]}>
                <T.Group name="toeR" position={[0, 0.15, 0]} rotation={[2.72, 0, Math.PI]} />
                <T.Group
                  name="heel02R"
                  position={[0.03, 0.01, 0.08]}
                  rotation={[2.72, 0, Math.PI / 2]}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group name="original_rig">
        <T is={gltf.nodes.root} />
        <T is={gltf.nodes['MCH-torsoparent']} />
        <T is={gltf.nodes['MCH-hand_ikparentL']} />
        <T is={gltf.nodes['MCH-upper_arm_ik_targetparentL']} />
        <T is={gltf.nodes['MCH-hand_ikparentR']} />
        <T is={gltf.nodes['MCH-upper_arm_ik_targetparentR']} />
        <T is={gltf.nodes['MCH-foot_ikparentL']} />
        <T is={gltf.nodes['MCH-thigh_ik_targetparentL']} />
        <T is={gltf.nodes['MCH-foot_ikparentR']} />
        <T is={gltf.nodes['MCH-thigh_ik_targetparentR']} />
        <T.SkinnedMesh
          name="chest001"
          geometry={gltf.nodes.chest001.geometry}
          material={fleshMaterial}
          skeleton={gltf.nodes.chest001.skeleton}
        />
        <T.SkinnedMesh
          name="stomach_pipes"
          geometry={gltf.nodes.stomach_pipes.geometry}
          material={metalMaterial}
          skeleton={gltf.nodes.stomach_pipes.skeleton}
        />
      </T.Group>
      <T.Mesh
        name="pelvis"
        geometry={gltf.nodes.pelvis.geometry}
        material={gltf.nodes.pelvis.material}
        position={[0, 0.99, -0.01]}
      >
        <T.Mesh
          name="Sphere"
          geometry={gltf.nodes.Sphere.geometry}
          material={gltf.nodes.Sphere.material}
          position={[0, 0.51, 0.01]}
          scale={[0.41, 0.51, 0.87]}
        />
        <T.Mesh
          name="Sphere004"
          geometry={gltf.nodes.Sphere004.geometry}
          material={gltf.nodes.Sphere004.material}
          position={[0.1, -0.06, 0]}
          rotation={[-0.05, 0, 0]}
          scale={2.16}
        />
      </T.Mesh>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
