<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 armature.glb --transform --types
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf, useGltfAnimations } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type ActionName = 'Bendy'
	type GLTFResult = {
		nodes: {
			Cube: THREE.SkinnedMesh
			One: THREE.Bone
		}
		materials: {
			Material: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/armature-transformed.glb', { useDraco: true })
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

	$: console.log($actions.Bendy)
	$: $actions.Bendy?.play()
	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Armature">
				<T is={gltf.nodes.One} />
				<T.SkinnedMesh
					name="Cube"
					geometry={gltf.nodes.Cube.geometry}
					material={gltf.materials.Material}
					skeleton={gltf.nodes.Cube.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
