<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 horse.glb --transform --types
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf, useGltfAnimations } from '@threlte/extras'

	type $$Props = Props<THREE.Group>
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type ActionName = 'Gallop' | 'Gallop.001'
	type GLTFResult = {
		nodes: {
			Saddle: THREE.Mesh
			Saddle_Pad: THREE.Mesh
			Horse: THREE.SkinnedMesh
			Bone: THREE.Bone
			Bone002: THREE.Bone
		}
		materials: {
			Material: THREE.MeshStandardMaterial
			Material: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/horse-transformed.glb', { useDraco: true })
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

	$: console.log($actions)
	$: $actions.Gallop?.play()

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Horse_Armature" position={[-0.29, 5, -0.49]} rotation={[1.59, -0.06, 0.01]}>
				<T is={gltf.nodes.Bone} />
				<T is={gltf.nodes.Bone002} />
				<T.SkinnedMesh
					name="Horse"
					geometry={gltf.nodes.Horse.geometry}
					material={gltf.materials.Material}
					skeleton={gltf.nodes.Horse.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
